-- gallery (category column in DB: type)
create table public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  type text not null check (type in ('Member', 'Conference', '기타')),
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gallery enable row level security;

drop policy if exists "gallery_public_read" on public.gallery;
drop policy if exists "gallery_authenticated_write" on public.gallery;
create policy "gallery_public_read" on public.gallery for select using (true);
create policy "gallery_authenticated_write" on public.gallery for all to authenticated using (true) with check (true);
