-- gallery (category column in DB: type)
create table public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  type text not null check (type in ('Member', 'Conference', '기타')),
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gallery enable row level security;

drop policy if exists "gallery_public_read" on public.gallery;
drop policy if exists "gallery_authenticated_write" on public.gallery;
create policy "gallery_public_read" on public.gallery for select using (true);
-- Write requires membership in public.admin_users (see admins.sql), not just
-- a signed-in account.
drop policy if exists "gallery_admin_write" on public.gallery;
create policy "gallery_admin_write" on public.gallery for all to authenticated using (public.is_admin()) with check (public.is_admin());
