-- members (professor profile lives in app localStorage, not this table)
create table public.members (
  id bigint generated by default as identity primary key,
  member_group text not null check (
    member_group in ('postdocs', 'gradStudents', 'phdAlumni', 'msAlumni')
  ),
  name_ko text not null,
  name_en text not null,
  degree text not null,
  email text,
  research text,
  graduation_date date,
  photo_url text,
  created_at timestamptz not null default now()
);

create index members_group_idx on public.members (member_group);

alter table public.members enable row level security;

drop policy if exists "members_public_read" on public.members;
drop policy if exists "members_authenticated_write" on public.members;
create policy "members_public_read" on public.members for select using (true);
create policy "members_authenticated_write" on public.members for all to authenticated using (true) with check (true);
