-- news_file (requires news)
create table public.news_file (
  id bigint generated by default as identity primary key,
  news_id bigint not null references public.news(id) on delete cascade,
  url text not null,
  file_name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index news_file_news_id_idx on public.news_file (news_id);

alter table public.news_file enable row level security;

drop policy if exists "news_file_public_read" on public.news_file;
drop policy if exists "news_file_authenticated_write" on public.news_file;
create policy "news_file_public_read" on public.news_file for select using (true);
create policy "news_file_authenticated_write" on public.news_file for all to authenticated using (true) with check (true);
