-- news
create table public.news (
  id bigint generated by default as identity primary key,
  type text not null,
  date text not null,
  title text not null,
  detail text not null,
  author text not null default '',
  view_count bigint not null default 0,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index news_pinned_idx on public.news (pinned) where pinned = true;

alter table public.news enable row level security;

drop policy if exists "news_public_read" on public.news;
drop policy if exists "news_authenticated_write" on public.news;
create policy "news_public_read" on public.news for select using (true);
create policy "news_authenticated_write" on public.news for all to authenticated using (true) with check (true);

-- RPC: increment view_count on detail page (anon-safe)
create or replace function public.increment_news_view_count(p_news_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  update public.news
  set view_count = view_count + 1
  where id = p_news_id
  returning view_count into new_count;

  return new_count;
end;
$$;

grant execute on function public.increment_news_view_count(bigint) to anon, authenticated;
