-- patents (date stored as text, YYYY-MM-DD recommended)
create table public.patents (
  id bigint generated by default as identity primary key,
  number text not null,
  title text not null,
  title_en text not null,
  date text not null,
  status text not null check (status in ('registered', 'pending')),
  inventors text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.patents enable row level security;

drop policy if exists "patents_public_read" on public.patents;
drop policy if exists "patents_authenticated_write" on public.patents;
create policy "patents_public_read" on public.patents for select using (true);
create policy "patents_authenticated_write" on public.patents for all to authenticated using (true) with check (true);
