-- publications
create table public.publications (
  id bigint generated by default as identity primary key,
  title_ko text not null,
  title_en text not null,
  authors text not null,
  journal text not null,
  doi text not null default '',
  doi_link text,
  published_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index publications_published_at_idx on public.publications (published_at desc);

alter table public.publications enable row level security;

drop policy if exists "publications_public_read" on public.publications;
drop policy if exists "publications_authenticated_write" on public.publications;
create policy "publications_public_read" on public.publications for select using (true);
create policy "publications_authenticated_write" on public.publications for all to authenticated using (true) with check (true);
