-- OEPL Supabase schema (user-defined)
-- id = bigint auto-increment

drop table if exists public.members cascade;
drop table if exists public.patents cascade;
drop table if exists public.gallery cascade;
drop table if exists public.publications cascade;
drop table if exists public.news cascade;

-- 1. news
create table public.news (
  id bigint generated by default as identity primary key,
  type text not null,
  date text not null,
  title text not null,
  detail text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. publications
create table public.publications (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('Journal', 'Conference')),
  title_ko text not null,
  title_en text not null,
  authors text not null,
  journal text not null,
  doi text not null default '',
  doi_link text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3. gallery (category stored as `type`)
create table public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  type text not null check (type in ('Member', 'Conference', '기타')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4. patents
create table public.patents (
  id bigint generated by default as identity primary key,
  number text not null,
  title text not null,
  title_en text not null,
  date text not null,
  status text not null check (status in ('registered', 'pending')),
  inventors text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5. members (unchanged)
create table public.members (
  id bigint generated by default as identity primary key,
  member_group text not null check (
    member_group in ('postdocs', 'gradStudents', 'phdAlumni', 'msAlumni')
  ),
  name_ko text not null,
  name_en text not null,
  degree text not null,
  email text,
  field_kr text,
  field_en text,
  graduation_date date,
  photo_url text,
  created_at timestamptz not null default now()
);

create index members_group_idx on public.members (member_group);

alter table public.news enable row level security;
alter table public.publications enable row level security;
alter table public.gallery enable row level security;
alter table public.patents enable row level security;
alter table public.members enable row level security;

create policy "news_public_read" on public.news for select using (true);
create policy "publications_public_read" on public.publications for select using (true);
create policy "gallery_public_read" on public.gallery for select using (true);
create policy "patents_public_read" on public.patents for select using (true);
create policy "members_public_read" on public.members for select using (true);

create policy "news_authenticated_write" on public.news for all to authenticated using (true) with check (true);
create policy "publications_authenticated_write" on public.publications for all to authenticated using (true) with check (true);
create policy "gallery_authenticated_write" on public.gallery for all to authenticated using (true) with check (true);
create policy "patents_authenticated_write" on public.patents for all to authenticated using (true) with check (true);
create policy "members_authenticated_write" on public.members for all to authenticated using (true) with check (true);
